spring.application.name=ms-usuarios
server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5432/usuarios_db
spring.datasource.username=ms_user
spring.datasource.password=ms_pass123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false